Main – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
Main Program
Source File
Uses:
Main_Sub
Main program entry.
Calls
Source Code
PROGRAM Main
  !< Main program entry.
  !
  USE Main_Sub
  !
  CALL Entry_Main_Sub ()
  !
END PROGRAM Main
Call graph
main calls entry_main_sub
entry_main_sub calls ooopimma_start
ooopimma_start calls ooopinma_start, ooogglob_subresetprocedures, iiimma_sync_checkactivityflag, ooopimma_structureconstructor, images, ooogglob_subsetprocedures
ooopinma_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiinma_loadteammanagers, ma_chrteammembersfiles99, ooopinma_structureconstructor, ma_intteammanagerimages99, ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiimma_sync_checkactivityflag calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimmcg_chrteammembersfilename_ca, oooptema_start, oooptmem_start, ooopimscg_intimageactivityflag_ca
ooopimma_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iiinma_loadteammanagers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ma_chrteammembersfiles99, ma_intteammanagerimages99, ooopstpag_chrpath, ooopstpa_loadpath, iiinma_errorhandler, ooopinmas_intnumberofteammanagers
ooopinma_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiinma_activateteammanagerimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooopimsc_structureconstructor_ca, ooopimmcs_chrteammembersfilename_ca
ooopstpag_chrpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopstpa_loadpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iistpa_errorhandler
iiinma_errorhandler calls oooeerroc_addobject
ooopinmas_intnumberofteammanagers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiinma_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
iiimsc_errorhandler calls oooeerroc_addobject
ooopimsc_structureconstructor_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
iiimmc_errorhandler calls oooeerroc_addobject
ooopimmcg_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
oooptema_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptemas_chrteammembersfilename, iitema_loadteammembers, ma_intteammemberimages99, iitema_activateteammemberimage, oooptema_structureconstructor
oooptmem_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptmem_structureconstructor
ooopimscg_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
oooptemas_chrteammembersfilename calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iitema_loadteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopstpag_chrpath, ooopstpa_loadpath, ma_intteammemberimages99, oooptemas_intnumberofteammembers, iitema_errorhandler
iitema_activateteammemberimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca
oooptema_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
oooptemas_intnumberofteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iitema_errorhandler
iitema_errorhandler calls oooeerroc_addobject
oooptmem_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures