IIimsc_ErrorHandler – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIimsc_ErrorHandler Subroutine
Source File
private subroutine IIimsc_ErrorHandler(Object, chrErrorDescription, intErrorType, intErrorNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimsc_adtImageStatus_CA), intent(inout) :: Object
character(kind=1,LEN=*), intent(in) :: chrErrorDescription
integer(kind=OOOGglob_kint), intent(in) :: intErrorType
integer(kind=OOOGglob_kint), intent(in) :: intErrorNumber
Calls
Called By
Source Code
SUBROUTINE IIimsc_ErrorHandler (Object, chrErrorDescription, &
  intErrorType, intErrorNumber)
  ! ErrorHandler for the ADT and CA routines
  TYPE(OOOPimsc_adtImageStatus_CA), INTENT(INOUT) :: Object
  CHARACTER(KIND=1, LEN=*), INTENT(IN) :: chrErrorDescription
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorType ! 1=warning, 2=Severe System error
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorNumber ! Run Time error Number (e.g. Status)
  CALL OOOEerroc_AddObject (Object % m_UUerrocError, chrErrorDescription, &
    intErrorType)
END SUBROUTINE IIimsc_ErrorHandler
Call graph
iiimsc_errorhandler calls oooeerroc_addobject
ooopimscdc_copycoarrayobjimgtoimg_ca calls iiimsc_errorhandler, ooopimsccopyimgtoimg_intimageactivityflag_ca
ooopimsccopyimgtoimg_intimageactivityflag_ca calls iiimsc_errorhandler
ooopimscs_intimageactivityflag_ca calls iiimsc_errorhandler
ooopimscg_intimageactivityflag_ca calls iiimsc_errorhandler
iiinma_activateteammanagerimage calls ooopimscs_intimageactivityflag_ca
oooptmem_start calls ooopimscs_intimageactivityflag_ca
oooptema_start calls ooopimscs_intimageactivityflag_ca, iitema_activateteammemberimage
iitema_activateteammemberimage calls ooopimscs_intimageactivityflag_ca
ooopinma_start calls ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiimma_sync_checkactivityflag calls ooopimscg_intimageactivityflag_ca, oooptmem_start, oooptema_start
ooopimma_start calls ooopinma_start, iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub