IIimsc_ImageNumberBoundError_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIimsc_ImageNumberBoundError_CA Function
Source File
private function IIimsc_ImageNumberBoundError_CA(Object_CA, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimsc_adtImageStatus_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Return Value logical(kind=OOOGglob_klog)
Called By
Source Code
LOGICAL(OOOGglob_klog) FUNCTION IIimsc_ImageNumberBoundError_CA (Object_CA, intImageNumber)
  ! error handling routine
  ! checks if the image number does exist
  TYPE(OOOPimsc_adtImageStatus_CA), CODIMENSION[*], INTENT(INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT(IN) :: intImageNumber
  !
  IIimsc_ImageNumberBoundError_CA = .FALSE.
  !
  IF (intImageNumber .LT. 1) THEN ! image number is too small
    IIimsc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
  IF (intImageNumber .GT. NUM_IMAGES()) THEN ! image number is too large
    IIimsc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
END FUNCTION IIimsc_ImageNumberBoundError_CA
Call graph
ooopimscdc_copycoarrayobjimgtoimg_ca calls iiimsc_imagenumberbounderror_ca, ooopimsccopyimgtoimg_intimageactivityflag_ca
ooopimsccopyimgtoimg_intimageactivityflag_ca calls iiimsc_imagenumberbounderror_ca
ooopimscs_intimageactivityflag_ca calls iiimsc_imagenumberbounderror_ca
ooopimscg_intimageactivityflag_ca calls iiimsc_imagenumberbounderror_ca
iiinma_activateteammanagerimage calls ooopimscs_intimageactivityflag_ca
oooptmem_start calls ooopimscs_intimageactivityflag_ca
oooptema_start calls ooopimscs_intimageactivityflag_ca, iitema_activateteammemberimage
iitema_activateteammemberimage calls ooopimscs_intimageactivityflag_ca
ooopinma_start calls ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiimma_sync_checkactivityflag calls ooopimscg_intimageactivityflag_ca, oooptmem_start, oooptema_start
ooopimma_start calls ooopinma_start, iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub