IIimmc_ImageNumberBoundError_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIimmc_ImageNumberBoundError_CA Function
Source File
public function IIimmc_ImageNumberBoundError_CA(Object_CA, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimmc_adtImageManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Return Value logical(kind=OOOGglob_klog)
Description
Called By
Source Code
LOGICAL(OOOGglob_klog) FUNCTION IIimmc_ImageNumberBoundError_CA (Object_CA, intImageNumber)
  ! error handling routine
  ! checks if the image number does exist
  TYPE(OOOPimmc_adtImageManager_CA), CODIMENSION[*], INTENT(INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT(IN) :: intImageNumber
  !
  IIimmc_ImageNumberBoundError_CA = .FALSE.
  !
  IF (intImageNumber .LT. 1) THEN ! image number is too small
    IIimmc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
  !********
  !
  IF (intImageNumber .GT. NUM_IMAGES()) THEN ! image number is too large
    IIimmc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
END FUNCTION IIimmc_ImageNumberBoundError_CA
Call graph
ooopimmcg_chrteammembersfilename_ca calls iiimmc_imagenumberbounderror_ca
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls iiimmc_imagenumberbounderror_ca
ooopimmcs_chrteammembersfilename_ca calls iiimmc_imagenumberbounderror_ca
ooopimmcs_intimageactivityflag_ca calls iiimmc_imagenumberbounderror_ca
ooopimmcdc_copycoarrayobjimgtoimg_ca calls iiimmc_imagenumberbounderror_ca, ooopimmccopyimgtoimg_chrteammembersfilename_ca, ooopimmccopyimgtoimg_intimageactivityflag_ca
ooopimmccopyimgtoimg_intimageactivityflag_ca calls iiimmc_imagenumberbounderror_ca
ooopimmcg_intimageactivityflag_ca calls iiimmc_imagenumberbounderror_ca
iiimma_sync_checkactivityflag calls ooopimmcg_chrteammembersfilename_ca
ooopimma_start calls iiimma_sync_checkactivityflag, ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub
iiinma_activateteammanagerimage calls ooopimmcs_chrteammembersfilename_ca
ooopinma_start calls iiinma_activateteammanagerimage