IIimmc_ErrorHandler – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIimmc_ErrorHandler Subroutine
Source File
private subroutine IIimmc_ErrorHandler(Object, chrErrorDescription, intErrorType, intErrorNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimmc_adtImageManager_CA), intent(inout) :: Object
character(kind=1,LEN=*), intent(in) :: chrErrorDescription
integer(kind=OOOGglob_kint), intent(in) :: intErrorType
integer(kind=OOOGglob_kint), intent(in) :: intErrorNumber
Calls
Called By
Source Code
SUBROUTINE IIimmc_ErrorHandler (Object, chrErrorDescription, &
  intErrorType, intErrorNumber)
  ! ErrorHandler for the ADT and CA routines
  TYPE(OOOPimmc_adtImageManager_CA), INTENT(INOUT) :: Object
  CHARACTER(KIND=1, LEN=*), INTENT(IN) :: chrErrorDescription
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorType ! 1=warning, 2=Severe System error
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorNumber ! Run Time error Number (e.g. Status)
  CALL OOOEerroc_AddObject (Object % m_UUerrocError, chrErrorDescription, &
    intErrorType)
END SUBROUTINE IIimmc_ErrorHandler
Call graph
iiimmc_errorhandler calls oooeerroc_addobject
ooopimmcg_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmcs_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmcs_intimageactivityflag_ca calls iiimmc_errorhandler
ooopimmcdc_copycoarrayobjimgtoimg_ca calls iiimmc_errorhandler, ooopimmccopyimgtoimg_chrteammembersfilename_ca, ooopimmccopyimgtoimg_intimageactivityflag_ca
ooopimmccopyimgtoimg_intimageactivityflag_ca calls iiimmc_errorhandler
ooopimmcg_intimageactivityflag_ca calls iiimmc_errorhandler
iiimma_sync_checkactivityflag calls ooopimmcg_chrteammembersfilename_ca
ooopimma_start calls iiimma_sync_checkactivityflag, ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub
iiinma_activateteammanagerimage calls ooopimmcs_chrteammembersfilename_ca
ooopinma_start calls iiinma_activateteammanagerimage