IIimma_SYNC_CheckActivityFlag – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIimma_SYNC_CheckActivityFlag Subroutine
Source File
private subroutine IIimma_SYNC_CheckActivityFlag(Object)
Uses:
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPimma_adtImageManager), intent(in) :: Object
Description
synchronization routine.
Synchronization counterpart routines are:
IIinma_ActivateTeamManagerImage
IItema_ActivateTeamMemberImage
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: intImageActivityFlag
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: chrTeamMembersFileName
Source Code
SUBROUTINE IIimma_SYNC_CheckActivityFlag (Object)
  !< synchronization routine.
  !
  !< Synchronization counterpart routines are:
  !<
  !< - IIinma_ActivateTeamManagerImage
  !< - IItema_ActivateTeamMemberImage
  USE OOOPimsc_admImageStatus_CA ! access corresponding coarrays to
                                 ! communicate with remote or local PGAS memory
  TYPE (OOOPimma_adtImageManager), INTENT (IN) :: Object
  INTEGER(OOOGglob_kint) :: intImageActivityFlag
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: chrTeamMembersFileName
  !
                                                                CALL OOOGglob_subSetProcedures ("IIimma_SYNC_CheckActivityFlag")
  !
  !
  DO ! check the ActivityFlag of the OOOPimscImageStatus_CA standalone coarray wrapper
     ! in local PGAS memory permanently until it is not InitialWaiting any more:
    CALL OOOPimscG_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, intImageActivityFlag, THIS_IMAGE())
    IF (intImageActivityFlag /= OOOPimscEnum_ImageActivityFlag % InitialWaiting) THEN
      EXIT
    END IF
  END DO
  !
  !
  DO ! 160414: check the ImageActivityFlag in local PGAS memory permanently until it has
     !         value OOOPimscEnum_ImageActivityFlag % ExecutionFinished
    ! 160414:
    CALL OOOPimscG_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, intImageActivityFlag, THIS_IMAGE())
    !
    IF (intImageActivityFlag == OOOPimscEnum_ImageActivityFlag % TeamManager) THEN   ! start a TeamManager
      CALL OOOPimmcG_chrTeamMembersFileName_CA (OOOPimmcImageManager_CA_1, chrTeamMembersFileName, THIS_IMAGE())
      CALL OOOPtema_Start (OOOPtemaTeamManager_1, chrTeamMembersFileName)
    END IF
    !
    IF (intImageActivityFlag == OOOPimscEnum_ImageActivityFlag % TeamMember) THEN   ! start a TeamMember
      CALL OOOPtmem_Start (OOOPtmemTeamMember_1)
    END IF
    ! 160414: finish image execution:
    IF (intImageActivityFlag == OOOPimscEnum_ImageActivityFlag % ExecutionFinished) THEN
      write(*,*) 'Execution finished on image', THIS_IMAGE()
      EXIT
    END IF
    !
  END DO ! 160414
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE IIimma_SYNC_CheckActivityFlag
Call graph
iiimma_sync_checkactivityflag calls ooopimmcg_chrteammembersfilename_ca, ooogglob_subresetprocedures, oooptema_start, oooptmem_start, ooopimscg_intimageactivityflag_ca, ooogglob_subsetprocedures
ooopimmcg_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
oooptema_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptemas_chrteammembersfilename, iitema_loadteammembers, ma_intteammemberimages99, iitema_activateteammemberimage, oooptema_structureconstructor
oooptmem_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptmem_structureconstructor
ooopimscg_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiimmc_errorhandler calls oooeerroc_addobject
ooopimscs_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
oooptemas_chrteammembersfilename calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iitema_loadteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ma_intteammemberimages99, ooopstpag_chrpath, oooptemas_intnumberofteammembers, iitema_errorhandler, ooopstpa_loadpath
iitema_activateteammemberimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca
oooptema_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iiimsc_errorhandler calls oooeerroc_addobject
ooopstpag_chrpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
oooptemas_intnumberofteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iitema_errorhandler
iitema_errorhandler calls oooeerroc_addobject
ooopstpa_loadpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iistpa_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
oooptmem_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub