IItemc_ErrorHandler – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IItemc_ErrorHandler Subroutine
Source File
private subroutine IItemc_ErrorHandler(Object, chrErrorDescription, intErrorType, intErrorNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout) :: Object
character(kind=1,LEN=*), intent(in) :: chrErrorDescription
integer(kind=OOOGglob_kint), intent(in) :: intErrorType
integer(kind=OOOGglob_kint), intent(in) :: intErrorNumber
Calls
Called By
Source Code
SUBROUTINE IItemc_ErrorHandler (Object, chrErrorDescription, &
  intErrorType, intErrorNumber)
  ! ErrorHandler for the ADT and CA routines
  TYPE(OOOPtemc_adtTeamManager_CA), INTENT(INOUT) :: Object
  CHARACTER(KIND=1, LEN=*), INTENT(IN) :: chrErrorDescription
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorType ! 1=warning, 2=Severe System error
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorNumber ! Run Time error Number (e.g. Status)
  CALL OOOEerroc_AddObject (Object % m_UUerrocError, chrErrorDescription, &
    intErrorType)
END SUBROUTINE IItemc_ErrorHandler
Call graph
iitemc_errorhandler calls oooeerroc_addobject
oooptemcdc_copycoarrayobjimgtoimg_ca calls iitemc_errorhandler, oooptemccopyaimgtoimg_intteammemberimages99_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca, oooptemccopyimgtoimg_chrteammembersfilename_ca
oooptemccopyaimgtoimg_intteammemberimages99_ca calls iitemc_errorhandler
oooptemccopyimgtoimg_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemcs_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemccopyimgtoimg_chrteammembersfilename_ca calls iitemc_errorhandler
oooptemcg_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemcs_chrteammembersfilename_ca calls iitemc_errorhandler
oooptemcg_chrteammembersfilename_ca calls iitemc_errorhandler