IItema_ActivateTeamMemberImage – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IItema_ActivateTeamMemberImage Subroutine
Source File
private subroutine IItema_ActivateTeamMemberImage(Object, intTeamMemberImageNumber)
Uses:
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPtema_adtTeamManager), intent(inout) :: Object
integer(kind=OOOGglob_kint), intent(in) :: intTeamMemberImageNumber
Calls
Called By
Source Code
SUBROUTINE IItema_ActivateTeamMemberImage (Object, intTeamMemberImageNumber) ! 160414
  !!!  synchronization counterpart routine  !!!!
  !!!  for IIimma_SYNC_CheckActivityFlag    !!!!
  ! starts a single TeamMember on its image
  !
  USE OOOPimsc_admImageStatus_CA ! access corresponding coarrays to
                                 ! communicate with remote or local PGAS memory
  TYPE (OOOPtema_adtTeamManager), INTENT (INOUT) :: Object
  INTEGER(OOOGglob_kint), INTENT(IN) :: intTeamMemberImageNumber ! 160414
  !
                                                                CALL OOOGglob_subSetProcedures ("IItema_ActivateTeamMemberImage")
  ! communicate with remote or local PGAS memory to activate a TeamMember image: 160414
  CALL OOOPimscS_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, OOOPimscEnum_ImageActivityFlag % TeamMember, &
                                                         intTeamMemberImageNumber) ! 160414
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE IItema_ActivateTeamMemberImage
Call graph
iitema_activateteammemberimage calls ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooogglob_subresetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiimsc_errorhandler calls oooeerroc_addobject
oooptema_start calls iitema_activateteammemberimage
iiimma_sync_checkactivityflag calls oooptema_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub