IItema_LoadTeamMembers – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IItema_LoadTeamMembers Subroutine
Source File
private subroutine IItema_LoadTeamMembers(Object)
Arguments
Type Intent Optional Attributes Name
type(OOOPtema_adtTeamManager), intent(inout) :: Object
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(OOOPstpa_adtStartPath), public :: UUStartPath1
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenStatus = 'OLD'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenAccess = 'SEQUENTIAL'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenForm = 'FORMATTED'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenPosition = 'REWIND'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenAction = 'READ'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenBlank = 'NULL'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len200), public :: chrStartPath
logical(kind=OOOGglob_klog), public :: logExist
integer(kind=OOOGglob_kint), public :: intRecl = 0
integer(kind=OOOGglob_kint), public :: FileUnit = 0
integer(kind=OOOGglob_kint), public :: FileStatus = 0
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len200), public :: chrPathAndFileName = ""
integer(kind=OOOGglob_kint), public :: intNumberOfTeamMembers
Source Code
SUBROUTINE IItema_LoadTeamMembers (Object)
  ! method, loads the data from TeamMembers_x.txt
  TYPE (OOOPtema_adtTeamManager), INTENT (INOUT) :: Object
  !
  TYPE (OOOPstpa_adtStartPath) :: UUStartPath1
  !
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenStatus = 'OLD'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenAccess  = 'SEQUENTIAL'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenForm = 'FORMATTED'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenPosition = 'REWIND'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenAction = 'READ'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenBlank = 'NULL'
  !
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len200) :: chrStartPath
  !
  ! for INQUIRE:
  LOGICAL(KIND=OOOGglob_klog) :: logExist
  INTEGER(OOOGglob_kint) :: intRecl = 0
  !
  INTEGER(OOOGglob_kint) :: FileUnit = 0
  INTEGER(OOOGglob_kint) :: FileStatus = 0 ! File-error-Status
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len200) :: chrPathAndFileName = ""
  INTEGER(OOOGglob_kint) :: intNumberOfTeamMembers
  !
                                                                CALL OOOGglob_subSetProcedures ("IItema_LoadTeamMembers")
  !
  FileUnit = OOOGglob_FileUnitA
  !
  ! get the path to the files directory:
  CALL OOOPstpa_LoadPath (UUStartPath1)
  CALL OOOPstpaG_chrPath (UUStartPath1, chrStartPath)
  !
  chrPathAndFileName = TRIM(chrStartPath) // Object % m_chrTeamMembersFileName
  !
  OPEN (UNIT=FileUnit, IOSTAT=FileStatus, FILE=TRIM(chrPathAndFileName), &
      STATUS=TRIM(OpenStatus), ACCESS=TRIM(OpenAccess), FORM=TRIM(OpenForm), &
      POSITION=TRIM(OpenPosition), ACTION=TRIM(OpenAction), &
      BLANK=TRIM(OpenBlank), DELIM='APOSTROPHE')
                                                                !
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IItema_ErrorHandler (Object, "File-Open-error", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  READ (UNIT=FileUnit, FMT=*, IOSTAT=FileStatus) intNumberOfTeamMembers
                                                                !
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IItema_ErrorHandler (Object, "File READ-Error 1", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  CALL OOOPtemaS_intNumberOfTeamMembers (Object, intNumberOfTeamMembers) ! contains error handling
  !
  ! read the TeamMember image numbers from file:
  READ (UNIT=FileUnit, FMT=*, IOSTAT=FileStatus) Object % mA_intTeamMemberImages99 (1 : Object % m_intNumberOfTeamMembers)
  !
                                                                IF (FileStatus /= 0) THEN
                                                                  ! FileStatus error
                                                                  CALL IItema_ErrorHandler (Object, "File READ-Error 2", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  CLOSE (UNIT=FileUnit, IOSTAT=FileStatus, STATUS='KEEP')
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IItema_ErrorHandler (Object, "File-Close-error", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
                                                                CALL OOOGglob_subResetProcedures
  !
END SUBROUTINE IItema_LoadTeamMembers
Call graph
iitema_loadteammembers calls iitema_errorhandler, ooogglob_subsetprocedures, oooptemas_intnumberofteammembers, ooogglob_subresetprocedures, ooopstpag_chrpath, ma_intteammemberimages99, ooopstpa_loadpath
iitema_errorhandler calls oooeerroc_addobject
oooptemas_intnumberofteammembers calls iitema_errorhandler, ooogglob_subsetprocedures, ooogglob_subresetprocedures
ooopstpag_chrpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
ooopstpa_loadpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iistpa_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
oooptema_start calls iitema_loadteammembers
iiimma_sync_checkactivityflag calls oooptema_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub