OOOEerroc_AddObject – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOEerroc_AddObject Subroutine
Source File
public subroutine OOOEerroc_AddObject(Collection, chrErrorDescription, intErrorType)
Arguments
Type Intent Optional Attributes Name
type(OOOEerroc_colError), intent(inout) :: Collection
Error collection.
character(kind=OOOGglob_kcha,LEN=*), intent(in) :: chrErrorDescription
Error description.
integer(kind=OOOGglob_kint), intent(in) :: intErrorType
Error code.
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len200), public :: chrSelection
Dummy string for handling user's input. Handle errors occurrence.
Note
Prompt user for errors-handling choice.
Source Code
SUBROUTINE OOOEerroc_AddObject (Collection, chrErrorDescription, &
  intErrorType)
  TYPE (OOOEerroc_colError),           INTENT(INOUT) :: Collection          !< Error collection.
  CHARACTER(KIND=OOOGglob_kcha,LEN=*), INTENT(IN)    :: chrErrorDescription !< Error description.
  INTEGER(KIND=OOOGglob_kint),         INTENT(IN)    :: intErrorType        !< Error code.
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len200)  :: chrSelection        !< Dummy string for handling user's input.
  !< Handle errors occurrence.
  !<
  !< @note Prompt user for errors-handling choice.
  !
  !
Write(*,*) "CurrentProc: ", OOOGglob_chrCurrentProcedure
!
write(*,*) "ErrDescr: ", TRIM(chrErrorDescription)
!
write(*,*)  "ErrTyp: ", intErrorType
!
Write(*,*)
Write(*,*) "CallingProc: ", TRIM(OOOGglob_chrCallingProcedure)
!
Write(*,*) "ReturningProc: ", TRIM(OOOGglob_chrReturningProcedure)
!
PRINT *
Write(*,*) "     *** An error occured ! *** "
PRINT *, ' Please select: '
PRINT *
PRINT *, ' x  - Exit Program, or'
PRINT *, ' c  - Continue Execution'
PRINT *
!
PRINT *, ' -> '
READ *, chrSelection
PRINT *
chrSelection = TRIM(chrSelection)
SELECT CASE (chrSelection)
  CASE ('x', 'X')
  !
      ERROR STOP ! end of execution
  !
END SELECT
!
END SUBROUTINE OOOEerroc_AddObject
Call graph
iitmec_errorhandler calls oooeerroc_addobject
iiimma_errorhandler calls oooeerroc_addobject
iistpa_errorhandler calls oooeerroc_addobject
iiimmc_errorhandler calls oooeerroc_addobject
iiinmc_errorhandler calls oooeerroc_addobject
iitemc_errorhandler calls oooeerroc_addobject
iitema_errorhandler calls oooeerroc_addobject
iiinma_errorhandler calls oooeerroc_addobject
iitmem_errorhandler calls oooeerroc_addobject
iiimsc_errorhandler calls oooeerroc_addobject
ooopstpa_loadpath calls iistpa_errorhandler
iitema_loadteammembers calls iitema_errorhandler, ooopstpa_loadpath, oooptemas_intnumberofteammembers
iiinma_loadteammanagers calls iiinma_errorhandler, ooopstpa_loadpath, ooopinmas_intnumberofteammanagers
oooptema_start calls iitema_loadteammembers, ooopimscs_intimageactivityflag_ca, iitema_activateteammemberimage
iiimma_sync_checkactivityflag calls oooptema_start, ooopimmcg_chrteammembersfilename_ca, ooopimscg_intimageactivityflag_ca, oooptmem_start
ooopimma_start calls iiimma_sync_checkactivityflag, ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub
ooopinma_start calls iiinma_loadteammanagers, iiinma_activateteammanagerimage, ooopimscs_intimageactivityflag_ca
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmcg_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmcdc_copycoarrayobjimgtoimg_ca calls iiimmc_errorhandler, ooopimmccopyimgtoimg_chrteammembersfilename_ca, ooopimmccopyimgtoimg_intimageactivityflag_ca
ooopimmcs_intimageactivityflag_ca calls iiimmc_errorhandler
ooopimmcs_chrteammembersfilename_ca calls iiimmc_errorhandler
ooopimmccopyimgtoimg_intimageactivityflag_ca calls iiimmc_errorhandler
ooopimmcg_intimageactivityflag_ca calls iiimmc_errorhandler
iiinma_activateteammanagerimage calls ooopimmcs_chrteammembersfilename_ca, ooopimscs_intimageactivityflag_ca
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls iiinmc_errorhandler
ooopinmcg_intnumberofteammanagers_ca calls iiinmc_errorhandler
ooopinmccopyaimgtoimg_chrteammembersfiles99_ca calls iiinmc_errorhandler
ooopinmccopyimgtoimg_intnumberofteammanagers_ca calls iiinmc_errorhandler
ooopinmcs_intnumberofteammanagers_ca calls iiinmc_errorhandler
ooopinmcdc_copycoarrayobjimgtoimg_ca calls iiinmc_errorhandler, ooopinmccopyaimgtoimg_intteammanagerimages99_ca, ooopinmccopyaimgtoimg_chrteammembersfiles99_ca, ooopinmccopyimgtoimg_intnumberofteammanagers_ca
oooptemcdc_copycoarrayobjimgtoimg_ca calls iitemc_errorhandler, oooptemccopyaimgtoimg_intteammemberimages99_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca, oooptemccopyimgtoimg_chrteammembersfilename_ca
oooptemccopyaimgtoimg_intteammemberimages99_ca calls iitemc_errorhandler
oooptemccopyimgtoimg_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemcs_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemccopyimgtoimg_chrteammembersfilename_ca calls iitemc_errorhandler
oooptemcg_intnumberofteammembers_ca calls iitemc_errorhandler
oooptemcs_chrteammembersfilename_ca calls iitemc_errorhandler
oooptemcg_chrteammembersfilename_ca calls iitemc_errorhandler
oooptemas_intnumberofteammembers calls iitema_errorhandler
ooopinmas_intnumberofteammanagers calls iiinma_errorhandler
ooopimsccopyimgtoimg_intimageactivityflag_ca calls iiimsc_errorhandler
ooopimscg_intimageactivityflag_ca calls iiimsc_errorhandler
ooopimscdc_copycoarrayobjimgtoimg_ca calls iiimsc_errorhandler, ooopimsccopyimgtoimg_intimageactivityflag_ca
ooopimscs_intimageactivityflag_ca calls iiimsc_errorhandler
oooptmem_start calls ooopimscs_intimageactivityflag_ca
iitema_activateteammemberimage calls ooopimscs_intimageactivityflag_ca