OOOGglob_subResetProcedures – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOGglob_subResetProcedures Subroutine
Source File
public subroutine OOOGglob_subResetProcedures()
Arguments
None
Description
Error-Handling and Tracing
Called By
Source Code
SUBROUTINE OOOGglob_subResetProcedures
  !< Error-Handling and Tracing
  ! refresh the Stack Trace:
  OOOGglob_intStackTraceCounter = OOOGglob_intStackTraceCounter - 1
  OOOGglob_chrCurrentProcedure = OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter)
  OOOGglob_chrReturningProcedure = OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter + 1)
  IF (OOOGglob_intStackTraceCounter > 1) THEN
    OOOGglob_chrCallingProcedure = OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter - 1)
  END IF
  !
END SUBROUTINE OOOGglob_subResetProcedures
Call graph
ooopinmcs_intnumberofteammanagers_ca calls ooogglob_subresetprocedures
oooptemccopyimgtoimg_chrteammembersfilename_ca calls ooogglob_subresetprocedures
ooopimma_start calls ooogglob_subresetprocedures, iiimma_sync_checkactivityflag, ooopinma_start, ooopimma_structureconstructor
oooptemag_chrteammembersfilename calls ooogglob_subresetprocedures
ooopinmccopyaimgtoimg_chrteammembersfiles99_ca calls ooogglob_subresetprocedures
ooopinmag_intnumberofteammanagers calls ooogglob_subresetprocedures
ooopinmcsa_intteammanagerimages99_ca calls ooogglob_subresetprocedures
oooptema_structureconstructor calls ooogglob_subresetprocedures
oooptemccopyimgtoimg_intnumberofteammembers_ca calls ooogglob_subresetprocedures
ooopimmcs_intimageactivityflag_ca calls ooogglob_subresetprocedures
ooopimsc_structureconstructor calls ooogglob_subresetprocedures
oooptemcga_intteammemberimages99_ca calls ooogglob_subresetprocedures
iiimma_sync_checkactivityflag calls ooogglob_subresetprocedures, oooptmem_start, oooptema_start, ooopimmcg_chrteammembersfilename_ca, ooopimscg_intimageactivityflag_ca
ooopinmc_structureconstructor calls ooogglob_subresetprocedures
oooptmem_start calls ooogglob_subresetprocedures, oooptmem_structureconstructor, ooopimscs_intimageactivityflag_ca
oooptemc_structureconstructor calls ooogglob_subresetprocedures
ooopinma_start calls ooogglob_subresetprocedures, iiinma_loadteammanagers, ooopimscs_intimageactivityflag_ca, ooopinma_structureconstructor, iiinma_activateteammanagerimage
oooptema_start calls ooogglob_subresetprocedures, oooptema_structureconstructor, oooptemas_chrteammembersfilename, ooopimscs_intimageactivityflag_ca, iitema_activateteammemberimage, iitema_loadteammembers
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls ooogglob_subresetprocedures
oooptmem_structureconstructor calls ooogglob_subresetprocedures
ooopinmcga_chrteammembersfiles99_ca calls ooogglob_subresetprocedures
oooptemcs_chrteammembersfilename_ca calls ooogglob_subresetprocedures
ooopimmcg_intimageactivityflag_ca calls ooogglob_subresetprocedures
ooopinmcg_intnumberofteammanagers_ca calls ooogglob_subresetprocedures
oooptmec_structureconstructor calls ooogglob_subresetprocedures
oooptemcg_chrteammembersfilename_ca calls ooogglob_subresetprocedures
ooopimma_structureconstructor calls ooogglob_subresetprocedures
iiinma_loadteammanagers calls ooogglob_subresetprocedures, ooopstpag_chrpath, ooopstpa_loadpath, ooopinmas_intnumberofteammanagers
ooopimscdc_copycoarrayobjimgtoimg_ca calls ooogglob_subresetprocedures, ooopimsccopyimgtoimg_intimageactivityflag_ca
ooopinmcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subresetprocedures, ooopinmccopyaimgtoimg_chrteammembersfiles99_ca, ooopinmccopyaimgtoimg_intteammanagerimages99_ca, ooopinmccopyimgtoimg_intnumberofteammanagers_ca
oooptemas_chrteammembersfilename calls ooogglob_subresetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subresetprocedures
ooopimmc_structureconstructor calls ooogglob_subresetprocedures
ooopimmcg_chrteammembersfilename_ca calls ooogglob_subresetprocedures
oooptemag_intnumberofteammembers calls ooogglob_subresetprocedures
ooopimsc_structureconstructor_ca calls ooogglob_subresetprocedures
ooopstpag_chrpath calls ooogglob_subresetprocedures
ooopinmcsa_chrteammembersfiles99_ca calls ooogglob_subresetprocedures
ooopimscg_intimageactivityflag_ca calls ooogglob_subresetprocedures
ooopinma_structureconstructor calls ooogglob_subresetprocedures
ooopimmccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subresetprocedures
oooptemcg_intnumberofteammembers_ca calls ooogglob_subresetprocedures
oooptemccopyaimgtoimg_intteammemberimages99_ca calls ooogglob_subresetprocedures
ooopimsccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subresetprocedures
ooopinmcga_intteammanagerimages99_ca calls ooogglob_subresetprocedures
oooptemcsa_intteammemberimages99_ca calls ooogglob_subresetprocedures
ooopstpa_loadpath calls ooogglob_subresetprocedures
oooptemas_intnumberofteammembers calls ooogglob_subresetprocedures
iitema_activateteammemberimage calls ooogglob_subresetprocedures, ooopimscs_intimageactivityflag_ca
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls ooogglob_subresetprocedures
oooptemcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subresetprocedures, oooptemccopyimgtoimg_chrteammembersfilename_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca, oooptemccopyaimgtoimg_intteammemberimages99_ca
iitema_loadteammembers calls ooogglob_subresetprocedures, ooopstpag_chrpath, ooopstpa_loadpath, oooptemas_intnumberofteammembers
ooopimmcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subresetprocedures, ooopimmccopyimgtoimg_intimageactivityflag_ca, ooopimmccopyimgtoimg_chrteammembersfilename_ca
iiinma_activateteammanagerimage calls ooogglob_subresetprocedures, ooopimscs_intimageactivityflag_ca, ooopimsc_structureconstructor_ca, ooopimmcs_chrteammembersfilename_ca
ooopinmas_intnumberofteammanagers calls ooogglob_subresetprocedures
ooopinmccopyimgtoimg_intnumberofteammanagers_ca calls ooogglob_subresetprocedures
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subresetprocedures
oooptemcs_intnumberofteammembers_ca calls ooogglob_subresetprocedures
ooopstpas_chrpath calls ooogglob_subresetprocedures
entry_main_sub calls ooopimma_start
main calls entry_main_sub