OOOPimmcDC_CopyCoarrayObjImgToImg_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimmcDC_CopyCoarrayObjImgToImg_CA Subroutine
Source File
public subroutine OOOPimmcDC_CopyCoarrayObjImgToImg_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPimmc_adtImageManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Description
copy the properties:
if necessary further properties must be copied here
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPimmcDC_CopyCoarrayObjImgToImg_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  ! copy from any (remote) image to any other (remote) image
  ! (static members only)
  TYPE (OOOPimmc_adtImageManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
  !******************************************
                                                                CALL OOOGglob_subSetProcedures  &
                                                                ("OOOPimmcDC_CopyCoarrayObjImgToImg_CA")
                                                                !
                                                                IF (IIimmc_ImageNumberBoundError_CA &
                                                                  (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IIimmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IIimmc_ImageNumberBoundError_CA &
                                                                  (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IIimmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                               !
  !*******************************************
  ! copy the properties:
  !****************
  CALL OOOPimmcCopyImgToImg_intImageActivityFlag_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  CALL OOOPimmcCopyImgToImg_chrTeamMembersFileName_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  ! if necessary further properties must be copied here
  !*******************************************
 !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimmcDC_CopyCoarrayObjImgToImg_CA
Call graph
ooopimmcdc_copycoarrayobjimgtoimg_ca calls ooopimmccopyimgtoimg_chrteammembersfilename_ca, ooogglob_subresetprocedures, iiimmc_imagenumberbounderror_ca, iiimmc_errorhandler, ooopimmccopyimgtoimg_intimageactivityflag_ca, ooogglob_subsetprocedures
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls ooogglob_subresetprocedures, iiimmc_imagenumberbounderror_ca, iiimmc_errorhandler, ooogglob_subsetprocedures
iiimmc_errorhandler calls oooeerroc_addobject
ooopimmccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subresetprocedures, iiimmc_imagenumberbounderror_ca, iiimmc_errorhandler, ooogglob_subsetprocedures