OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA Subroutine
Source File
public subroutine OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPinmc_adtInitialManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  TYPE (OOOPinmc_adtInitialManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA")
                                                                !
                                                                IF (IIinmc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IIinmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                !
                                                                IF (IIinmc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IIinmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  ! copy only the required part of the array:
                                                                !
                                                                IF (Object_CA % m_intNumberOfTeamManagers &
                                                                  .LT. 1) THEN
                                                                  CALL IIinmc_ErrorHandler (Object_CA, &
                                                                       "no valid number of TeamManagers", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  Object_CA[intImageNumberToCopyTo] % mA_intTeamManagerImages99 (1 : Object_CA % m_intNumberOfTeamManagers) &
   = Object_CA[intImageNumberToCopyFrom] % mA_intTeamManagerImages99 (1 : Object_CA % m_intNumberOfTeamManagers)
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA
Call graph
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls ooogglob_subsetprocedures, ma_intteammanagerimages99, ooogglob_subresetprocedures, iiinmc_imagenumberbounderror_ca, iiinmc_errorhandler
iiinmc_errorhandler calls oooeerroc_addobject
ooopinmcdc_copycoarrayobjimgtoimg_ca calls ooopinmccopyaimgtoimg_intteammanagerimages99_ca