OOOPtema_Start – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtema_Start Subroutine
Source File
public subroutine OOOPtema_Start(Object, chrTeamMembersFileName)
Uses:
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPtema_adtTeamManager), intent(inout) :: Object
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), intent(in) :: chrTeamMembersFileName
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: intTeamMemberImageNumber
integer(kind=OOOGglob_kint), public :: intCounter = 0
Source Code
SUBROUTINE OOOPtema_Start (Object, chrTeamMembersFileName)
  USE OOOPimsc_admImageStatus_CA ! access corresponding coarrays to
                                 ! communicate with remote or local PGAS memory
  TYPE (OOOPtema_adtTeamManager), INTENT (INOUT) :: Object
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40), INTENT (IN) :: chrTeamMembersFileName
  INTEGER(OOOGglob_kint) :: intTeamMemberImageNumber ! 160414
  INTEGER(OOOGglob_kint) :: intCounter = 0
  !
                                                                CALL OOOGglob_subSetProcedures ("OOOPtema_Start")
  !
  CALL OOOPtema_StructureConstructor (Object)
  !
write(*,*) 'TeamManager started on Image: ', THIS_IMAGE()
  !
  ! 160414:
  ! we do an early setting of the ImageActivityFlag at this place
  ! to allow supersession of the ExecutionFinished value later on:
  CALL OOOPimscS_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, OOOPimscEnum_ImageActivityFlag % &
                                                                      ExecutionFinished, THIS_IMAGE())
  !
  CALL OOOPtemaS_chrTeamMembersFileName (Object, chrTeamMembersFileName)
  CALL IItema_LoadTeamMembers (Object) ! from TeamMembers.txt
  !
  ! activate the TeamMembers on their images as given by TeamMembers_x.txt:
  DO intCounter = 1, Object % m_intNumberOfTeamMembers
    ! (mA_intTeamMemberImages99(intCounter) gives the (remote) image number of the TeamMember): 160414
    intTeamMemberImageNumber = Object % mA_intTeamMemberImages99(intCounter) ! 160414
    CALL IItema_ActivateTeamMemberImage (Object, intTeamMemberImageNumber) ! 160414
  END DO
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtema_Start
Call graph
oooptema_start calls oooptemas_chrteammembersfilename, ooopimscs_intimageactivityflag_ca, ooogglob_subsetprocedures, oooptema_structureconstructor, ooogglob_subresetprocedures, ma_intteammemberimages99, iitema_activateteammemberimage, iitema_loadteammembers
oooptemas_chrteammembersfilename calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
oooptema_structureconstructor calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
iitema_activateteammemberimage calls ooopimscs_intimageactivityflag_ca, ooogglob_subsetprocedures, ooogglob_subresetprocedures
iitema_loadteammembers calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, ma_intteammemberimages99, iitema_errorhandler, oooptemas_intnumberofteammembers, ooopstpag_chrpath, ooopstpa_loadpath
iiimsc_errorhandler calls oooeerroc_addobject
iitema_errorhandler calls oooeerroc_addobject
oooptemas_intnumberofteammembers calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iitema_errorhandler
ooopstpag_chrpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
ooopstpa_loadpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iistpa_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
iiimma_sync_checkactivityflag calls oooptema_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub