OOOPinma_Start – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPinma_Start Subroutine
Source File
public subroutine OOOPinma_Start(Object)
Uses:
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPinma_adtInitialManager), intent(inout) :: Object
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: intCounter = 0
Source Code
SUBROUTINE OOOPinma_Start (Object)
  USE OOOPimsc_admImageStatus_CA ! access corresponding coarrays to
                                 ! communicate with remote or local PGAS memory
  TYPE (OOOPinma_adtInitialManager), INTENT (INOUT) :: Object
  !
  INTEGER(OOOGglob_kint) :: intCounter = 0
  !
                                                                CALL OOOGglob_subSetProcedures ("OOOPinma_Start")
  !
  CALL OOOPinma_StructureConstructor (Object)
  !
  !*******
  CALL IIinma_LoadTeamManagers (Object) ! from TeamManagers.txt
  !
  ! activate the TeamManagers on the (remote) images as given by TeamManagers.txt:
  DO intCounter = 1, Object % m_intNumberOfTeamManagers
    ! (Object % mA_intTeamManagerImages99(intCounter) gives the (remote) image number)
    ! (Object % mA_chrTeamMembersFiles99(intCounter) gives the name of the file,
    !       containing the TeamManager's number of TeamMembers as well as the TeamMembers
    !       image numbers) :
    CALL IIinma_ActivateTeamManagerImage (Object, Object % mA_intTeamManagerImages99(intCounter), &
                                     Object % mA_chrTeamMembersFiles99(intCounter))
  END DO
  !
  !160414:
  ! communicate with local PGAS memory to finish image execution:
  CALL OOOPimscS_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, OOOPimscEnum_ImageActivityFlag % &
                                                                    ExecutionFinished, THIS_IMAGE())
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPinma_Start
Call graph
ooopinma_start calls ooogglob_subresetprocedures, iiinma_loadteammanagers, ma_chrteammembersfiles99, ooopinma_structureconstructor, ma_intteammanagerimages99, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiinma_loadteammanagers calls ooogglob_subresetprocedures, ma_chrteammembersfiles99, ma_intteammanagerimages99, ooogglob_subsetprocedures, ooopstpag_chrpath, ooopstpa_loadpath, iiinma_errorhandler, ooopinmas_intnumberofteammanagers
ooopinma_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiinma_activateteammanagerimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooopimsc_structureconstructor_ca, ooopimmcs_chrteammembersfilename_ca
ooopstpag_chrpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopstpa_loadpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iistpa_errorhandler
iiinma_errorhandler calls oooeerroc_addobject
ooopinmas_intnumberofteammanagers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiinma_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
iiimsc_errorhandler calls oooeerroc_addobject
ooopimsc_structureconstructor_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
iiimmc_errorhandler calls oooeerroc_addobject
ooopimma_start calls ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub