OOOPtema_StructureConstructor – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtema_StructureConstructor Subroutine
Source File
public subroutine OOOPtema_StructureConstructor(Object)
Arguments
Type Intent Optional Attributes Name
type(OOOPtema_adtTeamManager), intent(inout) :: Object
Calls
Called By
Source Code
SUBROUTINE OOOPtema_StructureConstructor (Object)
  ! structure constructor
  TYPE (OOOPtema_adtTeamManager), INTENT (INOUT) :: Object
  !
                                                                CALL OOOGglob_subSetProcedures ("OOOPtema_StructureConstructor")
  ! initialize something here
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtema_StructureConstructor
Call graph
oooptema_structureconstructor calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
oooptema_start calls oooptema_structureconstructor
iiimma_sync_checkactivityflag calls oooptema_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub