OOOPstpaG_chrPath – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPstpaG_chrPath Subroutine
Source File
public subroutine OOOPstpaG_chrPath(Object, chrPath)
Arguments
Type Intent Optional Attributes Name
type(OOOPstpa_adtStartPath), intent(in) :: Object
character(kind=OOOGglob_kcha,LEN=*), intent(out) :: chrPath
Calls
Called By
Source Code
SUBROUTINE OOOPstpaG_chrPath (Object, chrPath)
  TYPE (OOOPstpa_adtStartPath), INTENT (IN) :: Object
  CHARACTER(KIND=OOOGglob_kcha,LEN=*), INTENT (OUT) :: chrPath
                                                                CALL OOOGglob_subSetProcedures ("OOOPstpaG_chrPath")
  chrPath = Object % m_chrPath
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPstpaG_chrPath
Call graph
ooopstpag_chrpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
iiinma_loadteammanagers calls ooopstpag_chrpath
iitema_loadteammembers calls ooopstpag_chrpath
ooopinma_start calls iiinma_loadteammanagers
ooopimma_start calls ooopinma_start, iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub
oooptema_start calls iitema_loadteammembers
iiimma_sync_checkactivityflag calls oooptema_start