OOOPtemcS_intNumberOfTeamMembers_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtemcS_intNumberOfTeamMembers_CA Subroutine
Source File
public subroutine OOOPtemcS_intNumberOfTeamMembers_CA(Object_CA, intNumberOfTeamMembers, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intNumberOfTeamMembers
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPtemcS_intNumberOfTeamMembers_CA (Object_CA, intNumberOfTeamMembers, &
                                                   intImageNumber)
  TYPE (OOOPtemc_adtTeamManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intNumberOfTeamMembers
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumber
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                  ("OOOPtemcS_intNumberOfTeamMembers_CA")
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumber)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                   "no valid image number", &
                                                                     OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (intNumberOfTeamMembers > OOOGglob_TeamMembers_UpperBound) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, "to many elements", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  Object_CA[intImageNumber] % m_intNumberOfTeamMembers = intNumberOfTeamMembers
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtemcS_intNumberOfTeamMembers_CA
Call graph
oooptemcs_intnumberofteammembers_ca calls ooogglob_subsetprocedures, iitemc_errorhandler, ooogglob_subresetprocedures, iitemc_imagenumberbounderror_ca
iitemc_errorhandler calls oooeerroc_addobject