OOOPimmcG_intImageActivityFlag_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimmcG_intImageActivityFlag_CA Subroutine
Source File
public subroutine OOOPimmcG_intImageActivityFlag_CA(Object_CA, intImageActivityFlag, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimmc_adtImageManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(out) :: intImageActivityFlag
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPimmcG_intImageActivityFlag_CA (Object_CA, intImageActivityFlag, &
                                                intImageNumber)
  TYPE (OOOPimmc_adtImageManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (OUT) :: intImageActivityFlag
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumber
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPimmcG_intImageActivityFlag_CA")
                                                                !
                                                                IF (IIimmc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumber)) THEN
                                                                  CALL IIimmc_ErrorHandler (Object_CA, &
                                                                   "no valid image number", &
                                                                     OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  intImageActivityFlag = Object_CA[intImageNumber] % m_intImageActivityFlag
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimmcG_intImageActivityFlag_CA
Call graph
ooopimmcg_intimageactivityflag_ca calls ooogglob_subsetprocedures, iiimmc_imagenumberbounderror_ca, ooogglob_subresetprocedures, iiimmc_errorhandler
iiimmc_errorhandler calls oooeerroc_addobject