IIinmc_ImageNumberBoundError_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIinmc_ImageNumberBoundError_CA Function
Source File
private function IIinmc_ImageNumberBoundError_CA(Object_CA, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPinmc_adtInitialManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Return Value logical(kind=OOOGglob_klog)
Called By
Source Code
LOGICAL(OOOGglob_klog) FUNCTION IIinmc_ImageNumberBoundError_CA (Object_CA, intImageNumber)
  ! error handling routine
  ! checks if the image number does exist
  TYPE(OOOPinmc_adtInitialManager_CA), CODIMENSION[*], INTENT(INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT(IN) :: intImageNumber
  !
  IIinmc_ImageNumberBoundError_CA = .FALSE.
  !
  IF (intImageNumber .LT. 1) THEN ! image number is too small
    IIinmc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
  IF (intImageNumber .GT. NUM_IMAGES()) THEN ! image number is too large
    IIinmc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
END FUNCTION IIinmc_ImageNumberBoundError_CA
Call graph
ooopinmcdc_copycoarrayobjimgtoimg_ca calls iiinmc_imagenumberbounderror_ca, ooopinmccopyaimgtoimg_chrteammembersfiles99_ca, ooopinmccopyimgtoimg_intnumberofteammanagers_ca, ooopinmccopyaimgtoimg_intteammanagerimages99_ca
ooopinmccopyaimgtoimg_chrteammembersfiles99_ca calls iiinmc_imagenumberbounderror_ca
ooopinmcg_intnumberofteammanagers_ca calls iiinmc_imagenumberbounderror_ca
ooopinmcs_intnumberofteammanagers_ca calls iiinmc_imagenumberbounderror_ca
ooopinmccopyimgtoimg_intnumberofteammanagers_ca calls iiinmc_imagenumberbounderror_ca
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls iiinmc_imagenumberbounderror_ca