IIinma_ActivateTeamManagerImage – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIinma_ActivateTeamManagerImage Subroutine
Source File
private subroutine IIinma_ActivateTeamManagerImage(Object, intTeamManagerImageNumber, chrTeamMembersFileName)
Uses:
OOOPimmc_admImageManager_CA
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPinma_adtInitialManager), intent(in) :: Object
integer(kind=OOOGglob_kint), intent(in) :: intTeamManagerImageNumber
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), intent(in) :: chrTeamMembersFileName
Calls
Called By
Source Code
SUBROUTINE IIinma_ActivateTeamManagerImage (Object, intTeamManagerImageNumber, chrTeamMembersFileName)
  !!!  synchronization counterpart routine  !!!!
  !!!  for IIimma_SYNC_CheckActivityFlag    !!!!
  ! activate a TeamManager on a remote image (as given by TeamManagers.txt)
  !
  USE OOOPimmc_admImageManager_CA ! access corresponding coarrays to
  USE OOOPimsc_admImageStatus_CA  ! communicate with remote or local PGAS memory
  !
  TYPE (OOOPinma_adtInitialManager), INTENT (IN) :: Object
  INTEGER(OOOGglob_kint), INTENT(IN) :: intTeamManagerImageNumber
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40), INTENT(IN) :: chrTeamMembersFileName
  !
                                                                CALL OOOGglob_subSetProcedures ("IIinma_ActivateTeamManagerImage")
  !
  ! firstly, set up the required data on the remote image:
  CALL OOOPimmcS_chrTeamMembersFileName_CA (OOOPimmcImageManager_CA_1, chrTeamMembersFileName, &
                                                   intTeamManagerImageNumber)
  ! set the activity flag on the remote image:
  CALL OOOPimsc_StructureConstructor_CA (OOOPimscImageStatus_CA_1)
  CALL OOOPimscS_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, OOOPimscEnum_ImageActivityFlag % TeamManager, &
                                          intTeamManagerImageNumber)
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE IIinma_ActivateTeamManagerImage
Call graph
iiinma_activateteammanagerimage calls ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooopimmcs_chrteammembersfilename_ca, ooogglob_subresetprocedures, ooopimsc_structureconstructor_ca
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
ooopimsc_structureconstructor_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
iiimsc_errorhandler calls oooeerroc_addobject
iiimmc_errorhandler calls oooeerroc_addobject
ooopinma_start calls iiinma_activateteammanagerimage
ooopimma_start calls ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub