IIinma_LoadTeamManagers – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IIinma_LoadTeamManagers Subroutine
Source File
private subroutine IIinma_LoadTeamManagers(Object)
Arguments
Type Intent Optional Attributes Name
type(OOOPinma_adtInitialManager), intent(inout) :: Object
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(OOOPstpa_adtStartPath), public :: UUStartPath1
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenStatus = 'OLD'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenAccess = 'SEQUENTIAL'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenForm = 'FORMATTED'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenPosition = 'REWIND'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenAction = 'READ'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len40), public :: OpenBlank = 'NULL'
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len200), public :: chrStartPath
logical(kind=OOOGglob_klog), public :: logExist
integer(kind=OOOGglob_kint), public :: intRecl = 0
integer(kind=OOOGglob_kint), public :: FileUnit = 0
integer(kind=OOOGglob_kint), public :: FileStatus = 0
character(kind=OOOGglob_kcha,LEN=OOOGglob_Len200), public :: chrPathAndFileName = ""
integer(kind=OOOGglob_kint), public :: intCounter
integer(kind=OOOGglob_kint), public :: intNumberOfTeamManagers
Source Code
SUBROUTINE IIinma_LoadTeamManagers (Object)
  ! method, loads the data from TeamManagers.txt
  TYPE (OOOPinma_adtInitialManager), INTENT (INOUT) :: Object
  !
  TYPE (OOOPstpa_adtStartPath) :: UUStartPath1
  !
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenStatus = 'OLD'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenAccess  = 'SEQUENTIAL'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenForm = 'FORMATTED'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenPosition = 'REWIND'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenAction = 'READ'
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len40) :: OpenBlank = 'NULL'
  !
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len200) :: chrStartPath
  !
  ! for INQUIRE:
  LOGICAL(KIND=OOOGglob_klog) :: logExist
  INTEGER(OOOGglob_kint) :: intRecl = 0
  !
  INTEGER(OOOGglob_kint) :: FileUnit = 0
  INTEGER(OOOGglob_kint) :: FileStatus = 0 ! File-error-Status
  CHARACTER(KIND=OOOGglob_kcha,LEN=OOOGglob_Len200) :: chrPathAndFileName = ""
  INTEGER(OOOGglob_kint) :: intCounter ! do loop counter
  INTEGER(OOOGglob_kint) :: intNumberOfTeamManagers
  !
                                                                CALL OOOGglob_subSetProcedures ("IIinma_LoadTeamManagers")
  !
  FileUnit = OOOGglob_FileUnitA
  !
  CALL OOOPstpa_LoadPath (UUStartPath1)
  CALL OOOPstpaG_chrPath (UUStartPath1, chrStartPath)
  !
  chrPathAndFileName = TRIM(chrStartPath) // 'TeamManagers.txt'
  !
  OPEN (UNIT=FileUnit, IOSTAT=FileStatus, FILE=TRIM(chrPathAndFileName), &
      STATUS=TRIM(OpenStatus), ACCESS=TRIM(OpenAccess), FORM=TRIM(OpenForm), &
      POSITION=TRIM(OpenPosition), ACTION=TRIM(OpenAction), &
      BLANK=TRIM(OpenBlank), DELIM='APOSTROPHE')
                                                                !
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IIinma_ErrorHandler (Object, "File Open-error", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  READ (UNIT=FileUnit, FMT=*, IOSTAT=FileStatus) intNumberOfTeamManagers
                                                                !
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IIinma_ErrorHandler (Object, "File READ-Error 1", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  CALL OOOPinmaS_intNumberOfTeamManagers (Object, intNumberOfTeamManagers) ! contains error handling
  !
  ! read the TeamManagerImages and there TeamMembers file name from the TeamManagers.txt file
  DO intCounter = 1, Object % m_intNumberOfTeamManagers
    READ (UNIT=FileUnit, FMT=*, IOSTAT=FileStatus) Object % mA_intTeamManagerImages99 (intCounter), &
      Object % mA_chrTeamMembersFiles99 (intCounter)
    !
                                                                IF (FileStatus /= 0) THEN
                                                                  ! FileStatus error
                                                                  CALL IIinma_ErrorHandler (Object, "File READ-Error 2", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  END DO
  !
  CLOSE (UNIT=FileUnit, IOSTAT=FileStatus, STATUS='KEEP')
                                                                IF (FileStatus /= 0) THEN
                                                                  CALL IIinma_ErrorHandler (Object, "File-Close-error", &
                                                                    OOOGglob_error, FileStatus)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
                                                                CALL OOOGglob_subResetProcedures
  !
END SUBROUTINE IIinma_LoadTeamManagers
Call graph
iiinma_loadteammanagers calls ooopstpag_chrpath, ma_intteammanagerimages99, ooopinmas_intnumberofteammanagers, ooopstpa_loadpath, ma_chrteammembersfiles99, ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiinma_errorhandler
ooopstpag_chrpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
ooopinmas_intnumberofteammanagers calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiinma_errorhandler
ooopstpa_loadpath calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iistpa_errorhandler
iiinma_errorhandler calls oooeerroc_addobject
iistpa_errorhandler calls oooeerroc_addobject
ooopinma_start calls iiinma_loadteammanagers
ooopimma_start calls ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub