IItemc_ImageNumberBoundError_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IItemc_ImageNumberBoundError_CA Function
Source File
public function IItemc_ImageNumberBoundError_CA(Object_CA, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Return Value logical(kind=OOOGglob_klog)
Called By
Source Code
LOGICAL(OOOGglob_klog) FUNCTION IItemc_ImageNumberBoundError_CA (Object_CA, intImageNumber)
  ! error handling routine
  ! checks if the image number does exist
  TYPE(OOOPtemc_adtTeamManager_CA), CODIMENSION[*], INTENT(INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT(IN) :: intImageNumber
  !
  IItemc_ImageNumberBoundError_CA = .FALSE.
  !
  IF (intImageNumber .LT. 1) THEN ! image number is too small
    IItemc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
  IF (intImageNumber .GT. NUM_IMAGES()) THEN ! image number is too large
    IItemc_ImageNumberBoundError_CA = .TRUE.
  END IF
  !
END FUNCTION IItemc_ImageNumberBoundError_CA
Call graph
oooptemcdc_copycoarrayobjimgtoimg_ca calls iitemc_imagenumberbounderror_ca, oooptemccopyaimgtoimg_intteammemberimages99_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca, oooptemccopyimgtoimg_chrteammembersfilename_ca
oooptemccopyaimgtoimg_intteammemberimages99_ca calls iitemc_imagenumberbounderror_ca
oooptemccopyimgtoimg_intnumberofteammembers_ca calls iitemc_imagenumberbounderror_ca
oooptemcs_intnumberofteammembers_ca calls iitemc_imagenumberbounderror_ca
oooptemccopyimgtoimg_chrteammembersfilename_ca calls iitemc_imagenumberbounderror_ca
oooptemcg_intnumberofteammembers_ca calls iitemc_imagenumberbounderror_ca
oooptemcs_chrteammembersfilename_ca calls iitemc_imagenumberbounderror_ca
oooptemcg_chrteammembersfilename_ca calls iitemc_imagenumberbounderror_ca