IItema_ErrorHandler – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
IItema_ErrorHandler Subroutine
Source File
private subroutine IItema_ErrorHandler(Object, chrErrorDescription, intErrorType, intErrorNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPtema_adtTeamManager), intent(inout) :: Object
character(kind=1,LEN=*), intent(in) :: chrErrorDescription
integer(kind=OOOGglob_kint), intent(in) :: intErrorType
integer(kind=OOOGglob_kint), intent(in) :: intErrorNumber
Calls
Called By
Source Code
SUBROUTINE IItema_ErrorHandler (Object, chrErrorDescription, &
  intErrorType, intErrorNumber)
  ! ErrorHandler for the ADT-Routines
  TYPE(OOOPtema_adtTeamManager), INTENT(INOUT) :: Object
  CHARACTER(KIND=1, LEN=*), INTENT(IN) :: chrErrorDescription
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorType ! 1=warning, 2=Severe System error
  INTEGER(OOOGglob_kint), INTENT(IN) :: intErrorNumber ! Run Time error Number (e.g. Status)
  CALL OOOEerroc_AddObject (Object % m_UUerrocError, chrErrorDescription, &
    intErrorType)
END SUBROUTINE IItema_ErrorHandler
Call graph
iitema_errorhandler calls oooeerroc_addobject
iitema_loadteammembers calls iitema_errorhandler, oooptemas_intnumberofteammembers
oooptemas_intnumberofteammembers calls iitema_errorhandler
oooptema_start calls iitema_loadteammembers
iiimma_sync_checkactivityflag calls oooptema_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub