OOOGglob_subSetProcedures – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOGglob_subSetProcedures Subroutine
Source File
public subroutine OOOGglob_subSetProcedures(chrCurrentProcedure)
Arguments
Type Intent Optional Attributes Name
character(kind=OOOGglob_kcha,LEN=*), intent(in) :: chrCurrentProcedure
Current procedure name.
Description
Error-Handling and Tracing
Called By
Source Code
SUBROUTINE OOOGglob_subSetProcedures (chrCurrentProcedure)
  !< Error-Handling and Tracing
  CHARACTER(KIND=OOOGglob_kcha,LEN=*), INTENT(IN) :: chrCurrentProcedure !< Current procedure name.
  ! refresh the Stack Trace:
  OOOGglob_intStackTraceCounter = OOOGglob_intStackTraceCounter + 1
  OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter) = chrCurrentProcedure
  OOOGglob_chrCurrentProcedure = OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter)
  OOOGglob_chrCallingProcedure = OOOGglob_chrStackTrace (OOOGglob_intStackTraceCounter - 1)
  OOOGglob_chrReturningProcedure = ''
  !
END SUBROUTINE OOOGglob_subSetProcedures
Call graph
oooptema_structureconstructor calls ooogglob_subsetprocedures
oooptmem_start calls ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptmem_structureconstructor
oooptemag_chrteammembersfilename calls ooogglob_subsetprocedures
iiinma_activateteammanagerimage calls ooogglob_subsetprocedures, ooopimmcs_chrteammembersfilename_ca, ooopimscs_intimageactivityflag_ca, ooopimsc_structureconstructor_ca
ooopstpa_loadpath calls ooogglob_subsetprocedures
oooptemcg_chrteammembersfilename_ca calls ooogglob_subsetprocedures
ooopinmcg_intnumberofteammanagers_ca calls ooogglob_subsetprocedures
ooopinmcsa_intteammanagerimages99_ca calls ooogglob_subsetprocedures
ooopimsccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subsetprocedures
ooopimmcs_intimageactivityflag_ca calls ooogglob_subsetprocedures
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subsetprocedures
ooopinma_structureconstructor calls ooogglob_subsetprocedures
ooopimscdc_copycoarrayobjimgtoimg_ca calls ooogglob_subsetprocedures, ooopimsccopyimgtoimg_intimageactivityflag_ca
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures
ooopinmcs_intnumberofteammanagers_ca calls ooogglob_subsetprocedures
oooptemccopyaimgtoimg_intteammemberimages99_ca calls ooogglob_subsetprocedures
oooptemcg_intnumberofteammembers_ca calls ooogglob_subsetprocedures
ooopstpas_chrpath calls ooogglob_subsetprocedures
ooopinmas_intnumberofteammanagers calls ooogglob_subsetprocedures
oooptema_start calls ooogglob_subsetprocedures, oooptema_structureconstructor, ooopimscs_intimageactivityflag_ca, iitema_loadteammembers, iitema_activateteammemberimage, oooptemas_chrteammembersfilename
ooopimmcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subsetprocedures, ooopimmccopyimgtoimg_intimageactivityflag_ca, ooopimmccopyimgtoimg_chrteammembersfilename_ca
ooopimmccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subsetprocedures
ooopinmcsa_chrteammembersfiles99_ca calls ooogglob_subsetprocedures
ooopimma_structureconstructor calls ooogglob_subsetprocedures
ooopinmag_intnumberofteammanagers calls ooogglob_subsetprocedures
oooptemccopyimgtoimg_chrteammembersfilename_ca calls ooogglob_subsetprocedures
iiinma_loadteammanagers calls ooogglob_subsetprocedures, ooopstpa_loadpath, ooopinmas_intnumberofteammanagers, ooopstpag_chrpath
iiimma_sync_checkactivityflag calls ooogglob_subsetprocedures, oooptmem_start, oooptema_start, ooopimscg_intimageactivityflag_ca, ooopimmcg_chrteammembersfilename_ca
ooopimmccopyimgtoimg_chrteammembersfilename_ca calls ooogglob_subsetprocedures
oooptemcga_intteammemberimages99_ca calls ooogglob_subsetprocedures
ooopstpag_chrpath calls ooogglob_subsetprocedures
ooopinmcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subsetprocedures, ooopinmccopyaimgtoimg_chrteammembersfiles99_ca, ooopinmccopyaimgtoimg_intteammanagerimages99_ca, ooopinmccopyimgtoimg_intnumberofteammanagers_ca
oooptemccopyimgtoimg_intnumberofteammembers_ca calls ooogglob_subsetprocedures
oooptemag_intnumberofteammembers calls ooogglob_subsetprocedures
ooopimmc_structureconstructor calls ooogglob_subsetprocedures
ooopinmccopyaimgtoimg_chrteammembersfiles99_ca calls ooogglob_subsetprocedures
oooptemcsa_intteammemberimages99_ca calls ooogglob_subsetprocedures
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls ooogglob_subsetprocedures
oooptemcs_chrteammembersfilename_ca calls ooogglob_subsetprocedures
ooopinmccopyimgtoimg_intnumberofteammanagers_ca calls ooogglob_subsetprocedures
oooptemc_structureconstructor calls ooogglob_subsetprocedures
iitema_loadteammembers calls ooogglob_subsetprocedures, ooopstpa_loadpath, ooopstpag_chrpath, oooptemas_intnumberofteammembers
oooptemcs_intnumberofteammembers_ca calls ooogglob_subsetprocedures
ooopinma_start calls ooogglob_subsetprocedures, iiinma_activateteammanagerimage, ooopinma_structureconstructor, ooopimscs_intimageactivityflag_ca, iiinma_loadteammanagers
iitema_activateteammemberimage calls ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca
ooopinmcga_chrteammembersfiles99_ca calls ooogglob_subsetprocedures
oooptmem_structureconstructor calls ooogglob_subsetprocedures
ooopinmcga_intteammanagerimages99_ca calls ooogglob_subsetprocedures
ooopimscg_intimageactivityflag_ca calls ooogglob_subsetprocedures
oooptemas_intnumberofteammembers calls ooogglob_subsetprocedures
oooptemas_chrteammembersfilename calls ooogglob_subsetprocedures
oooptemcdc_copycoarrayobjimgtoimg_ca calls ooogglob_subsetprocedures, oooptemccopyaimgtoimg_intteammemberimages99_ca, oooptemccopyimgtoimg_chrteammembersfilename_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca
ooopimma_start calls ooogglob_subsetprocedures, ooopimma_structureconstructor, iiimma_sync_checkactivityflag, ooopinma_start
ooopimsc_structureconstructor calls ooogglob_subsetprocedures
ooopimmcg_intimageactivityflag_ca calls ooogglob_subsetprocedures
oooptmec_structureconstructor calls ooogglob_subsetprocedures
ooopimsc_structureconstructor_ca calls ooogglob_subsetprocedures
ooopimmcg_chrteammembersfilename_ca calls ooogglob_subsetprocedures
ooopinmc_structureconstructor calls ooogglob_subsetprocedures
entry_main_sub calls ooopimma_start
main calls entry_main_sub