OOOPtmem_Start – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtmem_Start Subroutine
Source File
public subroutine OOOPtmem_Start(Object)
Uses:
OOOPimsc_admImageStatus_CA
Arguments
Type Intent Optional Attributes Name
type(OOOPtmem_adtTeamMember), intent(inout) :: Object
Calls
Called By
Source Code
SUBROUTINE OOOPtmem_Start (Object)
  USE OOOPimsc_admImageStatus_CA ! access corresponding coarrays to
                                 ! communicate with remote or local PGAS memory
  TYPE (OOOPtmem_adtTeamMember), INTENT (INOUT) :: Object
  !
                                                                CALL OOOGglob_subSetProcedures ("OOOPtmem_Start")
  !
  CALL OOOPtmem_StructureConstructor (Object)
  !
write(*,*) 'TeamMember started on Image: ', THIS_IMAGE()
  !
  !160414:
  ! communicate with local PGAS memory to finish image execution:
  CALL OOOPimscS_intImageActivityFlag_CA (OOOPimscImageStatus_CA_1, OOOPimscEnum_ImageActivityFlag % &
                                                                      ExecutionFinished, THIS_IMAGE())
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtmem_Start
Call graph
oooptmem_start calls ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooogglob_subresetprocedures, oooptmem_structureconstructor
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
oooptmem_structureconstructor calls ooogglob_subsetprocedures, ooogglob_subresetprocedures
iiimsc_errorhandler calls oooeerroc_addobject
iiimma_sync_checkactivityflag calls oooptmem_start
ooopimma_start calls iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub