OOOPinmaS_intNumberOfTeamManagers – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPinmaS_intNumberOfTeamManagers Subroutine
Source File
public subroutine OOOPinmaS_intNumberOfTeamManagers(Object, intNumberOfTeamManagers)
Arguments
Type Intent Optional Attributes Name
type(OOOPinma_adtInitialManager), intent(inout) :: Object
integer(kind=OOOGglob_kint), intent(in) :: intNumberOfTeamManagers
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPinmaS_intNumberOfTeamManagers (Object, intNumberOfTeamManagers)
  TYPE (OOOPinma_adtInitialManager), INTENT (INOUT) :: Object
  INTEGER(OOOGglob_kint), INTENT (IN) :: intNumberOfTeamManagers
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures ("OOOPinmaS_intNumberOfTeamManagers")
                                                                !
                                                                IF (intNumberOfTeamManagers > OOOGglob_TeamManagers_UpperBound) THEN
                                                                  CALL IIinma_ErrorHandler (Object, "to many elements", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
  !
  Object % m_intNumberOfTeamManagers = intNumberOfTeamManagers
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPinmaS_intNumberOfTeamManagers
Call graph
ooopinmas_intnumberofteammanagers calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiinma_errorhandler
iiinma_errorhandler calls oooeerroc_addobject
iiinma_loadteammanagers calls ooopinmas_intnumberofteammanagers
ooopinma_start calls iiinma_loadteammanagers
ooopimma_start calls ooopinma_start
entry_main_sub calls ooopimma_start
main calls entry_main_sub