OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA Subroutine
Source File
public subroutine OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  TYPE (OOOPtemc_adtTeamManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA")
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  ! copy only the required part of the array:
  Object_CA[intImageNumberToCopyTo] % mA_intTeamMemberImages99 (1 : Object_CA % m_intNumberOfTeamMembers) &
   = Object_CA[intImageNumberToCopyFrom] % mA_intTeamMemberImages99 (1 : Object_CA % m_intNumberOfTeamMembers)
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA
Call graph
oooptemccopyaimgtoimg_intteammemberimages99_ca calls ma_intteammemberimages99, ooogglob_subsetprocedures, ooogglob_subresetprocedures, iitemc_imagenumberbounderror_ca, iitemc_errorhandler
iitemc_errorhandler calls oooeerroc_addobject
oooptemcdc_copycoarrayobjimgtoimg_ca calls oooptemccopyaimgtoimg_intteammemberimages99_ca