OOOPtemcDC_CopyCoarrayObjImgToImg_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtemcDC_CopyCoarrayObjImgToImg_CA Subroutine
Source File
public subroutine OOOPtemcDC_CopyCoarrayObjImgToImg_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Description
copy the properties:
if necessary further properties must be copied here
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPtemcDC_CopyCoarrayObjImgToImg_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  ! copy from any (remote) image to any other (remote) image
  ! (static members only)
  TYPE (OOOPtemc_adtTeamManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
  !******************************************
                                                                CALL OOOGglob_subSetProcedures  &
                                                                ("OOOPtemcDC_CopyCoarrayObjImgToImg_CA")
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  !*******************************************
  ! copy the properties:
  !****************
  CALL OOOPtemcCopyImgToImg_chrTeamMembersFileName_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  CALL OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  CALL OOOPtemcCopyAImgToImg_intTeamMemberImages99_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  ! if necessary further properties must be copied here
  !*******************************************
 !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtemcDC_CopyCoarrayObjImgToImg_CA
Call graph
oooptemcdc_copycoarrayobjimgtoimg_ca calls iitemc_imagenumberbounderror_ca, iitemc_errorhandler, oooptemccopyaimgtoimg_intteammemberimages99_ca, oooptemccopyimgtoimg_intnumberofteammembers_ca, oooptemccopyimgtoimg_chrteammembersfilename_ca, ooogglob_subsetprocedures, ooogglob_subresetprocedures
iitemc_errorhandler calls oooeerroc_addobject
oooptemccopyaimgtoimg_intteammemberimages99_ca calls iitemc_imagenumberbounderror_ca, iitemc_errorhandler, ooogglob_subsetprocedures, ooogglob_subresetprocedures, ma_intteammemberimages99
oooptemccopyimgtoimg_intnumberofteammembers_ca calls iitemc_imagenumberbounderror_ca, iitemc_errorhandler, ooogglob_subsetprocedures, ooogglob_subresetprocedures
oooptemccopyimgtoimg_chrteammembersfilename_ca calls iitemc_imagenumberbounderror_ca, iitemc_errorhandler, ooogglob_subsetprocedures, ooogglob_subresetprocedures