OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA Subroutine
Source File
public subroutine OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPtemc_adtTeamManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  TYPE (OOOPtemc_adtTeamManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA")
  !
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IItemc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IItemc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  Object_CA[intImageNumberToCopyTo] % m_intNumberOfTeamMembers = Object_CA[intImageNumberToCopyFrom] % m_intNumberOfTeamMembers
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPtemcCopyImgToImg_intNumberOfTeamMembers_CA
Call graph
oooptemccopyimgtoimg_intnumberofteammembers_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iitemc_imagenumberbounderror_ca, iitemc_errorhandler
iitemc_errorhandler calls oooeerroc_addobject
oooptemcdc_copycoarrayobjimgtoimg_ca calls oooptemccopyimgtoimg_intnumberofteammembers_ca