OOOPimma_Start – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimma_Start Subroutine
Source File
public subroutine OOOPimma_Start(Object)
Arguments
Type Intent Optional Attributes Name
type(OOOPimma_adtImageManager), intent(inout) :: Object
Abstract image manager.
Description
Start image manager.
Calls
Called By
Source Code
SUBROUTINE OOOPimma_Start (Object)
  !< Start image manager.
  TYPE (OOOPimma_adtImageManager), INTENT (INOUT) :: Object !< Abstract image manager.
  !
                                                                CALL OOOGglob_subSetProcedures ("OOOPimma_Start")
  !
  CALL OOOPimma_StructureConstructor (Object)
  SYNC ALL
  !
  IF (THIS_IMAGE() == 1) THEN
    ! on image 1 only: check if the number of images is not less 4,
    ! as a minimum requirement:
    IF (NUM_IMAGES() .LT. 4) THEN
      WRITE(*,*) ' **************************************'
      WRITE(*,*) ' ** Total number of images is to small: ', NUM_IMAGES(), '. '
      WRITE(*,*) ' ** Total number of images must be greater'
      WRITE(*,*) ' ** than 3 for the program to execute !'
      WRITE(*,*) ' **** program execution stopped *******'
      WRITE(*,*) ' **************************************'
      ERROR STOP ! STOP only, crashes the Linux terminal window
    END IF
    !
    SYNC IMAGES(*) ! all other images will wait for the executing image (image 1)
                    ! to reach this (but do not wait for each other)
  ELSE
    SYNC IMAGES(1) ! image 1 will wait for each of the other (executing) images to reach this
  END IF
  !********
  IF (THIS_IMAGE() .GT. 1) THEN
    CALL IIimma_SYNC_CheckActivityFlag (Object) ! synchronization routine
  ELSE
    CALL OOOPinma_Start (OOOPinmaInitialManager_1) ! start the InitialManager on image 1
    ! 160414:
    CALL IIimma_SYNC_CheckActivityFlag (Object) ! synchronization routine, will finish execution on image 1
                                                ! due to the call of subroutine IIinma_FinishExecution earlier
                                                ! in subroutine OOOPinma_Start
  END IF
    !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimma_Start
Call graph
ooopimma_start calls ooopinma_start, ooogglob_subresetprocedures, iiimma_sync_checkactivityflag, ooopimma_structureconstructor, images, ooogglob_subsetprocedures
ooopinma_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiinma_loadteammanagers, ma_chrteammembersfiles99, ooopinma_structureconstructor, ma_intteammanagerimages99, ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiimma_sync_checkactivityflag calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimmcg_chrteammembersfilename_ca, oooptema_start, oooptmem_start, ooopimscg_intimageactivityflag_ca
ooopimma_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iiinma_loadteammanagers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ma_chrteammembersfiles99, ma_intteammanagerimages99, ooopstpag_chrpath, ooopstpa_loadpath, iiinma_errorhandler, ooopinmas_intnumberofteammanagers
ooopinma_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimscs_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiinma_activateteammanagerimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, ooopimsc_structureconstructor_ca, ooopimmcs_chrteammembersfilename_ca
ooopstpag_chrpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopstpa_loadpath calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iistpa_errorhandler
iiinma_errorhandler calls oooeerroc_addobject
ooopinmas_intnumberofteammanagers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiinma_errorhandler
iistpa_errorhandler calls oooeerroc_addobject
iiimsc_errorhandler calls oooeerroc_addobject
ooopimsc_structureconstructor_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
ooopimmcs_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
iiimmc_errorhandler calls oooeerroc_addobject
ooopimmcg_chrteammembersfilename_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimmc_errorhandler, iiimmc_imagenumberbounderror_ca
oooptema_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptemas_chrteammembersfilename, iitema_loadteammembers, ma_intteammemberimages99, iitema_activateteammemberimage, oooptema_structureconstructor
oooptmem_start calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca, oooptmem_structureconstructor
ooopimscg_intimageactivityflag_ca calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
oooptemas_chrteammembersfilename calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
iitema_loadteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopstpag_chrpath, ooopstpa_loadpath, ma_intteammemberimages99, oooptemas_intnumberofteammembers, iitema_errorhandler
iitema_activateteammemberimage calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, ooopimscs_intimageactivityflag_ca
oooptema_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
oooptemas_intnumberofteammembers calls ooogglob_subresetprocedures, ooogglob_subsetprocedures, iitema_errorhandler
iitema_errorhandler calls oooeerroc_addobject
oooptmem_structureconstructor calls ooogglob_subresetprocedures, ooogglob_subsetprocedures
entry_main_sub calls ooopimma_start
main calls entry_main_sub