OOOPimscS_intImageActivityFlag_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimscS_intImageActivityFlag_CA Subroutine
Source File
public subroutine OOOPimscS_intImageActivityFlag_CA(Object_CA, intImageActivityFlag, intImageNumber)
Arguments
Type Intent Optional Attributes Name
type(OOOPimsc_adtImageStatus_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageActivityFlag
integer(kind=OOOGglob_kint), intent(in) :: intImageNumber
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPimscS_intImageActivityFlag_CA (Object_CA, intImageActivityFlag, &
                                                   intImageNumber)
  TYPE (OOOPimsc_adtImageStatus_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageActivityFlag
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumber
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPimscS_intImageActivityFlag_CA")
                                                                !
                                                                IF (IIimsc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumber)) THEN
                                                                  CALL IIimsc_ErrorHandler (Object_CA, &
                                                                       "no valid image number", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  Object_CA[intImageNumber] % m_intImageActivityFlag = intImageActivityFlag
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimscS_intImageActivityFlag_CA
Call graph
ooopimscs_intimageactivityflag_ca calls ooogglob_subsetprocedures, ooogglob_subresetprocedures, iiimsc_errorhandler, iiimsc_imagenumberbounderror_ca
iiimsc_errorhandler calls oooeerroc_addobject
oooptema_start calls ooopimscs_intimageactivityflag_ca, iitema_activateteammemberimage
ooopinma_start calls ooopimscs_intimageactivityflag_ca, iiinma_activateteammanagerimage
iiinma_activateteammanagerimage calls ooopimscs_intimageactivityflag_ca
oooptmem_start calls ooopimscs_intimageactivityflag_ca
iitema_activateteammemberimage calls ooopimscs_intimageactivityflag_ca
iiimma_sync_checkactivityflag calls oooptema_start, oooptmem_start
ooopimma_start calls ooopinma_start, iiimma_sync_checkactivityflag
entry_main_sub calls ooopimma_start
main calls entry_main_sub