OOOPimscDC_CopyCoarrayObjImgToImg_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimscDC_CopyCoarrayObjImgToImg_CA Subroutine
Source File
public subroutine OOOPimscDC_CopyCoarrayObjImgToImg_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPimsc_adtImageStatus_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Description
copy the properties:
if necessary further properties must be copied here
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPimscDC_CopyCoarrayObjImgToImg_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  ! copy from any (remote) image to any other (remote) image
  ! (static members only)
  TYPE (OOOPimsc_adtImageStatus_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
  !******************************************
                                                                CALL OOOGglob_subSetProcedures  &
                                                                ("OOOPimscDC_CopyCoarrayObjImgToImg_CA")
                                                                !
                                                                IF (IIimsc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IIimsc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IIimsc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IIimsc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  !*******************************************
  ! copy the properties:
  !****************
  CALL OOOPimscCopyImgToImg_intImageActivityFlag_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  ! if necessary further properties must be copied here
  !*******************************************
 !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimscDC_CopyCoarrayObjImgToImg_CA
Call graph
ooopimscdc_copycoarrayobjimgtoimg_ca calls ooogglob_subsetprocedures, ooopimsccopyimgtoimg_intimageactivityflag_ca, iiimsc_errorhandler, ooogglob_subresetprocedures, iiimsc_imagenumberbounderror_ca
ooopimsccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subsetprocedures, iiimsc_errorhandler, ooogglob_subresetprocedures, iiimsc_imagenumberbounderror_ca
iiimsc_errorhandler calls oooeerroc_addobject