OOOPinmcDC_CopyCoarrayObjImgToImg_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPinmcDC_CopyCoarrayObjImgToImg_CA Subroutine
Source File
public subroutine OOOPinmcDC_CopyCoarrayObjImgToImg_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPinmc_adtInitialManager_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Description
copy the properties:
if necessary further properties must be copied here
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPinmcDC_CopyCoarrayObjImgToImg_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  ! copy from any (remote) image to any other (remote) image
  ! (static members only)
  TYPE (OOOPinmc_adtInitialManager_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
  !******************************************
                                                                CALL OOOGglob_subSetProcedures  &
                                                                ("OOOPinmcDC_CopyCoarrayObjImgToImg_CA")
                                                                !
                                                                IF (IIinmc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IIinmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                !
                                                                IF (IIinmc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IIinmc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  !*******************************************
  ! copy the properties:
  !****************
  CALL OOOPinmcCopyImgToImg_intNumberOfTeamManagers_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  CALL OOOPinmcCopyAImgToImg_intTeamManagerImages99_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  CALL OOOPinmcCopyAImgToImg_chrTeamMembersFiles99_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  !****************
  ! if necessary further properties must be copied here
  !*******************************************
 !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPinmcDC_CopyCoarrayObjImgToImg_CA
Call graph
ooopinmcdc_copycoarrayobjimgtoimg_ca calls ooopinmccopyaimgtoimg_intteammanagerimages99_ca, ooogglob_subresetprocedures, iiinmc_imagenumberbounderror_ca, iiinmc_errorhandler, ooopinmccopyaimgtoimg_chrteammembersfiles99_ca, ooopinmccopyimgtoimg_intnumberofteammanagers_ca, ooogglob_subsetprocedures
ooopinmccopyaimgtoimg_intteammanagerimages99_ca calls ooogglob_subresetprocedures, iiinmc_imagenumberbounderror_ca, iiinmc_errorhandler, ooogglob_subsetprocedures, ma_intteammanagerimages99
iiinmc_errorhandler calls oooeerroc_addobject
ooopinmccopyaimgtoimg_chrteammembersfiles99_ca calls ooogglob_subresetprocedures, iiinmc_imagenumberbounderror_ca, iiinmc_errorhandler, ooogglob_subsetprocedures, ma_chrteammembersfiles99
ooopinmccopyimgtoimg_intnumberofteammanagers_ca calls ooogglob_subresetprocedures, iiinmc_imagenumberbounderror_ca, iiinmc_errorhandler, ooogglob_subsetprocedures