OOOPimscCopyImgToImg_intImageActivityFlag_CA – MPMD-with-Coarray-Fortran-Load-Balancing-Example-Program
OOOPimscCopyImgToImg_intImageActivityFlag_CA Subroutine
Source File
public subroutine OOOPimscCopyImgToImg_intImageActivityFlag_CA(Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
Arguments
Type Intent Optional Attributes Name
type(OOOPimsc_adtImageStatus_CA), intent(inout), CODIMENSION[*] :: Object_CA
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyFrom
integer(kind=OOOGglob_kint), intent(in) :: intImageNumberToCopyTo
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=OOOGglob_kint), public :: Status = 0
Source Code
SUBROUTINE OOOPimscCopyImgToImg_intImageActivityFlag_CA (Object_CA, intImageNumberToCopyFrom, intImageNumberToCopyTo)
  TYPE (OOOPimsc_adtImageStatus_CA), CODIMENSION[*], INTENT (INOUT) :: Object_CA
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyFrom
  INTEGER(OOOGglob_kint), INTENT (IN) :: intImageNumberToCopyTo
  INTEGER(OOOGglob_kint) :: Status = 0 ! error status
                                                                CALL OOOGglob_subSetProcedures &
                                                                 ("OOOPimscCopyImgToImg_intImageActivityFlag_CA")
                                                                !
                                                                IF (IIimsc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyFrom)) THEN
                                                                  CALL IIimsc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 1", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
                                                                IF (IIimsc_ImageNumberBoundError_CA &
                                                                (Object_CA, intImageNumberToCopyTo)) THEN
                                                                  CALL IIimsc_ErrorHandler (Object_CA, &
                                                                       "no valid image number 2", &
                                                                    OOOGglob_error, Status)
                                                                  CALL OOOGglob_subResetProcedures
                                                                  RETURN
                                                                END IF
                                                                !
  !
  Object_CA[intImageNumberToCopyTo] % m_intImageActivityFlag = Object_CA[intImageNumberToCopyFrom] % m_intImageActivityFlag
  !
                                                                CALL OOOGglob_subResetProcedures
END SUBROUTINE OOOPimscCopyImgToImg_intImageActivityFlag_CA
Call graph
ooopimsccopyimgtoimg_intimageactivityflag_ca calls ooogglob_subsetprocedures, iiimsc_errorhandler, ooogglob_subresetprocedures, iiimsc_imagenumberbounderror_ca
iiimsc_errorhandler calls oooeerroc_addobject
ooopimscdc_copycoarrayobjimgtoimg_ca calls ooopimsccopyimgtoimg_intimageactivityflag_ca